# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build-docker-singularity:
    jobs:
      - build-image:
          context: dockerhub
jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run: |
          echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker build -t roblhall/singularity:$SINGULARITY_VERSION singularity/
          
          docker push roblhall/singularity:$SINGULARITY_VERSION
