# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build-docker-singularity:
    jobs:
      - build-image:
          context: dockerhub
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Login to Dockerhub"
          command: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          
      - run:
          name: "Build Singularity container version $SINGULARITY_VERSION"
          command: docker build -t roblhall/singularity:$SINGULARITY_VERSION singularity/
          
      - run:
          name: "Push image to Dockerhub"
          command: docker push roblhall/singularity:$SINGULARITY_VERSION
          
